print qq~
Since I know that folks will try to install
this without reading the README, I'll reiterate
this here.

This is a web based (CGI) application, and 
does not have an installation, really, since
installation will differ depending on what
OS and HTTP server you are running, and where
you want the thing to live.

Please see information and installation 
instructions in the readme file, and in 
readme.html

Rich Bowen
rbowen\@rcbowen.com
RCBowen.com
--------
~;
